package com.project.repo;

import java.util.Optional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import com.project.entity.BankAdmin;

@Repository
public interface BankAdminRepo extends JpaRepository<BankAdmin, Long> {
    Optional<BankAdmin> findByEmail(String email);

    // looks up the BankAdmin by the nested User.username (generated by JPA property path)
    Optional<BankAdmin> findByUser_Username(String username);
}
